services:
  open-web-calendar:
    image: open-web-calendar
    build: .
    ports:
      - '8080:80'
    environment:
      - APP_DEBUG=False
    restart: unless-stopped
    networks:
      - static-site_default

networks:
  static-site_default:
    external: true
