version: '3'
services:
  open-web-calendar:
    image: open-web-calendar
    build: .
    ports:
      - '8080:80'
    environment:
      - ALLOWED_HOSTS=owc.queerreferat-aachen.de
      - APP_DEBUG=False
    restart: unless-stopped
    networks:
      - owc

networks:
  owc:
    driver: bridge
